# basic options
title: ewoks jekyll blog
author: Konrad Wessalowski
email: k.wessalowski@gmx.de
description: A wonderful site
github_username:  ewok187

# Build settings
markdown: kramdown
theme: minima
